# Generated by Django 5.1.4 on 2025-02-09 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='decription',
            field=models.CharField(default=1, max_length=100, verbose_name='описание'),
            preserve_default=False,
        ),
    ]
