# Generated by Django 5.1.4 on 2025-02-19 03:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0003_product_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='цена'),
        ),
        migrations.CreateModel(
            name='AtCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='дата добавления')),
                ('updated_at', models.DateField(auto_now=True, verbose_name='дата изменения')),
                ('name', models.CharField(max_length=100, verbose_name='название')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='at_category', to='board.category', verbose_name='выберите категорию')),
            ],
            options={
                'verbose_name': 'под категория',
                'verbose_name_plural': 'под категории',
            },
        ),
    ]
