# Generated by Django 5.1.4 on 2025-02-19 04:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0005_atcategory_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='at_category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='product', to='board.atcategory', verbose_name='выберите категорию'),
            preserve_default=False,
        ),
    ]
