# Generated by Django 5.1.4 on 2025-04-25 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0007_product_author'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'permissions': [('add_to_cart', 'Can add product to cart')], 'verbose_name': 'товар', 'verbose_name_plural': 'товары'},
        ),
    ]
